#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-arpack_combined_all
Version  : 0.1
Release  : 2
URL      : https://repo1.maven.org/maven2/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.jar
Source0  : https://repo1.maven.org/maven2/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.jar
Source1  : https://repo1.maven.org/maven2/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: mvn-arpack_combined_all-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-arpack_combined_all package.
Group: Data

%description data
data components for the mvn-arpack_combined_all package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.jar
/usr/share/java/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.pom
